delay:
  max_delay: 10
  weights:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
demand:
  base_demand_matrix:
  - - 172680.0
    - 64810.0
    - 64810.0
    - 64810.0
    - 64810.0
    - 64810.0
    - 64809.0
  - - 73077.0
    - 172683.0
    - 68943.0
    - 68943.0
    - 68943.0
    - 68943.0
    - 68943.0
  - - 73077.0
    - 68943.0
    - 172683.0
    - 68943.0
    - 68943.0
    - 68943.0
    - 68943.0
  - - 73077.0
    - 68943.0
    - 68943.0
    - 172683.0
    - 68943.0
    - 68943.0
    - 68943.0
  - - 73077.0
    - 68943.0
    - 68943.0
    - 68943.0
    - 172683.0
    - 68943.0
    - 68943.0
  - - 73077.0
    - 68943.0
    - 68943.0
    - 68943.0
    - 68943.0
    - 172683.0
    - 68943.0
  - - 73076.0
    - 68943.0
    - 68943.0
    - 68943.0
    - 68943.0
    - 68943.0
    - 172685.0
  epsilon_matrix:
  - - 0.0
    - 15.684139780509678
    - 13.348801819773593
    - 10.300560412578548
    - 11.530689979586286
    - 13.107024624515555
    - 2.912427342009055
  - - 8.351255450354468
    - 0.0
    - 6.3469588230898335
    - 1.0522982042879185
    - 4.931261932258927
    - 4.695497555576377
    - 2.4469690775921844
  - - 13.504590495402084
    - 13.241687477119251
    - 0.0
    - 3.316378355203687
    - 7.252413395216047
    - 11.296035763009877
    - 8.140567596155918
  - - 12.154985531174914
    - 5.301519913516497
    - 14.528613200411836
    - 0.0
    - 2.6288835511762816
    - 8.150468047812542
    - 15.082783573990929
  - - 3.428227013457569
    - 13.273541689206853
    - 2.5184022101752035
    - 10.712321359443663
    - 0.0
    - 8.903426163426792
    - 14.942002721678296
  - - 3.984770203302208
    - 1.5341120231367587
    - 10.778279187320614
    - 10.029663115338037
    - 10.212067039006087
    - 0.0
    - 15.588946742425863
  - - 9.922243747755127
    - 0.19611003747588462
    - 3.338868948364137
    - 15.602762784005929
    - 15.11827915267686
    - 2.640259759766966
    - 0.0
  lambda_matrix:
  - - 15.3325782085697
    - 11.061590489551177
    - 9.735147348264208
    - 15.363486383443949
    - 8.585514389986843
    - 0.19065464163669787
    - 5.695166566970958
  - - 13.148103695399357
    - 7.953653037338588
    - 0.23574300008886517
    - 1.0230392872506666
    - 9.512303784059375
    - 10.006371847934048
    - 10.370721566366328
  - - 6.340892664879796
    - 15.869336214233453
    - 2.440669930901322
    - 1.5875201934680128
    - 14.091685720377253
    - 3.247759784819067
    - 1.0661814455468797
  - - 3.6470915294298685
    - 10.589663506685998
    - 7.59082241267366
    - 1.7321223790663147
    - 6.02332256365373
    - 12.830261701551096
    - 7.250340150265091
  - - 12.034103803118649
    - 8.90143898547699
    - 14.783602534157016
    - 8.442626723529031
    - 11.789735556526352
    - 5.285438149564291
    - 6.633911363321136
  - - 0.33058510500472593
    - 5.705955104164591
    - 8.563914059120343
    - 13.59610740755516
    - 4.955874720190472
    - 8.343404352196435
    - 11.394363496100922
  - - 15.033471340727026
    - 4.56378608267684
    - 4.412658752928257
    - 3.4000673072876832
    - 2.1412536288111035
    - 3.0305745017653365
    - 13.490966399308736
network:
  num_shards: 7
shards:
- g_max: 2000000
  id: 0
- g_max: 2000000
  id: 1
- g_max: 2000000
  id: 2
- g_max: 2000000
  id: 3
- g_max: 2000000
  id: 4
- g_max: 2000000
  id: 5
- g_max: 2000000
  id: 6
simulation:
  delta: 0.128993359375
  demand_shock:
    enabled: true
    end_step: 101
    multiplier: 15
    start_step: 100
    target_shards:
    - 0
  l_target: 0.5
  perturbation:
    enabled: false
  total_steps: 2000
