delay:
  max_delay: 9
  weights: &id001
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
demand:
  alpha_j_history: *id001
  base_demand_matrix:
  - - 881000.0
    - 8000.0
    - 8000.0
    - 8000.0
    - 8000.0
    - 8000.0
    - 8000.0
  - - 11833.333333333334
    - 881000.0
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
  - - 11833.333333333334
    - 9916.666666666668
    - 881000.0
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
  - - 11833.333333333334
    - 9916.666666666668
    - 9916.666666666668
    - 881000.0
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
  - - 11833.333333333334
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
    - 881000.0
    - 9916.666666666668
    - 9916.666666666668
  - - 11833.333333333334
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
    - 881000.0
    - 9916.666666666668
  - - 11833.333333333334
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
    - 9916.666666666668
    - 881000.0
  epsilon_matrix:
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  lambda_matrix:
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
  - - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
    - 16.0
network:
  num_shards: 7
shards:
- g_max: 2000000
  id: 0
- g_max: 2000000
  id: 1
- g_max: 2000000
  id: 2
- g_max: 2000000
  id: 3
- g_max: 2000000
  id: 4
- g_max: 2000000
  id: 5
- g_max: 2000000
  id: 6
simulation:
  delta: 0.1330000000000001
  demand_shock:
    enabled: true
    end_step: 101
    multiplier: 15
    start_step: 100
    target_shards:
    - 0
  l_target: 0.5
  perturbation:
    enabled: false
  total_steps: 5000
