simulation:
  total_steps: 5000
  l_target: 0.5
  delta: 0.125
  perturbation:
    enabled: false
  demand_shock:
    enabled: true
    start_step: 100
    end_step: 101
    multiplier: 15
    target_shards: [0]

network:
  num_shards: 7

shards:
  - id: 0
    g_max: 2000000 
  - id: 1
    g_max: 2000000    
  - id: 2
    g_max: 2000000    
  - id: 3
    g_max: 2000000
  - id: 4
    g_max: 2000000
  - id: 5
    g_max: 2000000
  - id: 6
    g_max: 2000000

demand:
  base_demand_matrix:
  # will be subsetted during iteration
    - [300000, 350000, 350000, 200000, 200000, 200000, 200000]
    - [0, 300000, 175000, 150000, 150000, 150000, 150000]
    - [0, 175000, 300000, 150000, 150000, 150000, 150000]
    - [0, 150000, 150000, 300000, 175000, 175000, 175000]
    - [0, 150000, 150000, 175000, 300000, 175000, 175000]
    - [0, 150000, 150000, 175000, 175000, 300000, 175000]
    - [0, 150000, 150000, 175000, 175000, 175000, 300000]

  epsilon_matrix:
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]

  lambda_matrix:
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    - [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    
delay:
  max_delay: 5
  weights: [0, 0, 0, 0, 1]


