delay:
  max_delay: 5
  weights:
  - 0
  - 0
  - 0
  - 0
  - 1
demand:
  base_demand_matrix:
  - - 130000.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 145000.0
    - 130000.0
    - 72500.0
    - 72500.0
    - 72500.0
    - 72500.0
    - 72500.0
  - - 145000.0
    - 72500.0
    - 130000.0
    - 72500.0
    - 72500.0
    - 72500.0
    - 72500.0
  - - 145000.0
    - 72500.0
    - 72500.0
    - 130000.0
    - 72500.0
    - 72500.0
    - 72500.0
  - - 145000.0
    - 72500.0
    - 72500.0
    - 72500.0
    - 130000.0
    - 72500.0
    - 72500.0
  - - 145000.0
    - 72500.0
    - 72500.0
    - 72500.0
    - 72500.0
    - 130000.0
    - 72500.0
  - - 145000.0
    - 72500.0
    - 72500.0
    - 72500.0
    - 72500.0
    - 72500.0
    - 130000.0
  epsilon_matrix:
  - - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 5.0
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 5.0
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 5.0
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 5.0
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 5.0
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 5.0
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  lambda_matrix:
  - - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
  - - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
    - 1.5
network:
  num_shards: 7
shards:
- g_max: 2000000
  id: 0
- g_max: 2000000
  id: 1
- g_max: 2000000
  id: 2
- g_max: 2000000
  id: 3
- g_max: 2000000
  id: 4
- g_max: 2000000
  id: 5
- g_max: 2000000
  id: 6
simulation:
  delta: 0.125
  demand_shock:
    enabled: true
    end_step: 101
    multiplier: 15
    start_step: 100
    target_shards:
    - 0
  l_target: 0.5
  perturbation:
    enabled: false
  total_steps: 5000
